
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: alexandr999/devops-for-programmers-project-74  
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
    command: sh -c "
      sleep 5 &&
      make test"  
    depends_on:
      - db 

      
  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "./data:/var/lib/postgresql/data"
