
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: alexandr999/devops-for-programmers-project-74  
    command: make test  
    environment:
     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
     - DATABASE_NAME=${DATABASE_NAME}
     - DATABASE_USERNAME=${DATABASE_USERNAME}
     - DATABASE_PORT=${DATABASE_PORT}
     - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - db 

      
  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     - POSTGRES_USER=${DATABASE_USERNAME}
     - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"  
