
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: alexandr999/devops-for-programmers-project-74  
    command: make test  
    environment:
        - DATABASE_HOST=${DATABASE_HOST-db}
        - DATABASE_NAME=${DATABASE_NAME-postgres}
        - DATABASE_USERNAME=${DATABASE_USERNAME-postgres}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD-password}
        - DATABASE_PORT=${DATABASE_PORT-5432}
    depends_on:
      - db 
      
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password  
